name: asv benchmarks

on: [push]

jobs:
  build:

    runs-on: [self-hosted, Linux, x64]

    steps:
    - name: Activate conda
      run: |
        conda activate
    - name: Checks latest commit for regression
      run: |
        asv machine --yes
        asv continuous HEAD
