name: asv benchmarks

on: [push]

jobs:
  build:

    runs-on: [self-hosted, Linux, x64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Checks latest commit for regression
      run: |
        source /home/marti/miniconda3/bin/activate
        asv continuous HEAD
