name: Test conda channels

on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
  
    steps:
      - run: conda config --show channels

      - run: conda config --remove-key channels

      - run: conda config --add channels conda-forge

      - run: conda config --show channels
